[package]
name = "restate-metadata-store"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
options_schema = ["dep:schemars"]
test-util = []

[dependencies]
codederror = { workspace = true }
restate-core = { workspace = true }
restate-grpc-util = { workspace = true }
restate-node-protocol = { workspace = true }
restate-types = { workspace = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true }
bytestring = { workspace = true }
derive_builder = { workspace = true }
futures = { workspace = true }
humantime = { workspace = true }
hyper = { workspace = true, features = ["full"] }
prost = { workspace = true }
prost-types = { workspace = true }
rocksdb = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true, features = ["transport", "codegen", "prost"] }
tonic-reflection = { workspace = true }
tonic-health = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true, features = ["trace"] }
tracing = { workspace = true }


[dev-dependencies]
restate-core = { workspace = true, features = ["test-util"] }

anyhow = { workspace = true }
flexbuffers = { workspace = true }
googletest = { workspace = true }
tempfile = { workspace = true }
test-log = { workspace = true }
tracing-subscriber = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
