[package]
name = "restate-metadata-store"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
test-util = ["restate-types/test-util"]
grpc-client = ["tonic/transport", "tonic/gzip", "tonic/zstd", "prost"]
grpc-server = ["tonic/server", "prost"]

[dependencies]
restate-workspace-hack = { workspace = true }

restate-time-util = { workspace = true }
restate-types = { workspace = true }

async-trait = { workspace = true }
bytes = { workspace = true }
bytestring = { workspace = true }
metrics = { workspace = true }
prost = { workspace = true, optional = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true, optional = true, features = ["codegen", "prost"] }
tracing = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
