apiVersion: v2
name: restate-helm
description: Deploy a Restate cluster on Kubernetes
type: application
version: "1.5.5-dev"
home: https://restate.dev
sources:
  - https://github.com/restatedev/restate
icon: https://restate.dev/restate.png
