replicaCount: 1
nameOverride: "restate"
version: "" # pin a specific version

image:
  repository: docker.io/restatedev/restate
  pullPolicy: IfNotPresent

imagePullSecrets: [ ]

serviceAccount:
  create: true
  annotations: { }
podAnnotations: { }

podSecurityContext:
  fsGroup: 2000
  fsGroupChangePolicy: "OnRootMismatch"
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 3000


logging:
  env_filter: info,restate=debug

env:
  - name: RESTATE_TRACING__LOG_FORMAT
    value: Json

service:
  type: ClusterIP
  annotations: { }

resources:
  limits:
    cpu: 1
    memory: 3Gi
  requests:
    cpu: 500m
    memory: 1Gi

storage:
  size: 64Gi
  # -- Storage class to be used.
  # If defined, storageClassName: <storageClass>.
  # If set to "-", storageClassName: "", which disables dynamic provisioning.
  # If empty or set to null, no storageClassName spec is set, choosing the default provisioner.
  storageClassName: null

serviceMonitor:
  enabled: false
  path: /metrics
  scheme: http
