[package]
name = "meta"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Config
clap = { workspace = true }

# Async
drain = { workspace = true }
futures = { workspace = true }
futures_util = { workspace = true }
tokio = { workspace = true, features = ["full"] }

# Rest API
hyper = { workspace = true, features = ["full"] }
axum = "0.6.2"

# Serde
serde = { workspace = true }
serde_with = "2.2"
serde_json = "1.0"

# Service discovery and metadata
common = { workspace = true }
service_key_extractor = { workspace = true }
service_metadata = { workspace = true }
service_protocol = { workspace = true, features = ["discovery"] }
prost-reflect = { workspace = true }

# Others
tracing = { workspace = true }
thiserror = { workspace = true }