[package]
name = "meta"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
drain = { workspace = true }
futures = { workspace = true }
futures_util = { workspace = true }
hyper = { workspace = true, features = ["full"] }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
thiserror = { workspace = true }

axum = "0.6.2"

serde = { workspace = true }
serde_with = "2.2"
serde_json = "1.0"

common = { workspace = true }
service_key_extractor = { workspace = true }
ingress_grpc = { workspace = true }
service_protocol = { workspace = true, features = ["discovery"] }