[package]
name = "restate_invoker"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
options_schema = ["dep:schemars", "restate_common/options_schema"]

[dependencies]
bytes = { workspace = true }
bytes-utils = { workspace = true }
restate_common = { workspace = true, features = ["serde"] }
drain = { workspace = true }
futures = { workspace = true }
hyper = { workspace = true, features = ["http1", "http2", "client", "tcp", "stream", "runtime"] }
hyper-rustls = { workspace = true }
humantime = { workspace = true }
h2 = { version = "0.3.15", features = ["unstable"] }
paste = { workspace = true }
prost = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
serde_with = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-http = { workspace = true }

codederror = { workspace = true }
restate_errors = { workspace = true }
restate_journal = { workspace = true }
restate_service_metadata = { workspace = true }
restate_service_protocol = { workspace = true, features = ["message"] }
restate_timer_queue = { workspace = true }

[dev-dependencies]
uuid = { workspace = true }
restate_test_util = { workspace = true }
tracing-subscriber = { workspace = true }

restate_service_protocol = { workspace = true, features = ["codec"] }
