[package]
name = "restatectl"
version.workspace = true
authors.workspace = true
description = "Restate administration tools"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[package.metadata.dist]
dist = true
formula = "restatectl"

[features]
default = ["replicated-loglet", "local-loglet", "memory-loglet", "no-trace-logging"]
replicated-loglet = [
    "restate-bifrost/replicated-loglet",
]
memory-loglet = ["restate-types/memory-loglet", "restate-bifrost/memory-loglet", "restate-admin/memory-loglet"]
local-loglet = ["restate-bifrost/local-loglet", "restate-admin/local-loglet"]
no-trace-logging = ["tracing/max_level_trace", "tracing/release_max_level_debug"]

[dependencies]
restate-admin = { workspace = true, features = ["clients"] }
restate-bifrost = { workspace = true }
restate-cli-util = { workspace = true }
restate-core = { workspace = true }
restate-log-server = { workspace = true, features = ["clients"] }
restate-metadata-server = { workspace = true }
restate-rocksdb = { workspace = true }
restate-types = { workspace = true, features = ["clap"] }
restate-wal-protocol = { workspace = true }

anyhow = { workspace = true }
arrow = { workspace = true }
arrow-ipc = { version = "54.2.1" }
bytes = { workspace = true }
bytesize = { workspace = true }
bytestring = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = ["derive", "env", "wrap_help", "color", "std", "suggestions", "usage"] }
clap-stdin = "0.5.1"
cling = { workspace = true }
crossterm = { version = "0.27.0" }
ctrlc = { version = "3.4" }
diff = "0.1.13"
enumset = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
itertools = { workspace = true }
json-patch = "2.0.0"
humantime = { workspace = true }
lambda_runtime = "0.13.0"
prost-types = { workspace = true }
rand = { workspace = true }
rlimit = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true, features = ["transport", "prost", "zstd", "gzip"] }
tracing = { workspace = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[build-dependencies]
vergen = { version = "8", default-features = false, features = [
    "build",
    "git",
    "gitcl",
    "cargo",
] }

[dev-dependencies]
restate-local-cluster-runner = { workspace = true }
restate-test-util = { workspace = true }

googletest = { workspace = true }