[package]
name = "restatectl"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = ["replicated-loglet", "memory-loglet"]
replicated-loglet = [
    "restate-types/replicated-loglet",
    "restate-bifrost/replicated-loglet",
]
memory-loglet = ["restate-types/memory-loglet", "restate-bifrost/memory-loglet", "restate-admin/memory-loglet"]

[dependencies]
restate-admin = { workspace = true, features = ["clients"] }
restate-bifrost = { workspace = true }
restate-cli-util = { workspace = true }
restate-core = { workspace = true }
restate-metadata-store = { workspace = true }
restate-rocksdb = { workspace = true }
restate-tracing-instrumentation = { workspace = true }
restate-types = { workspace = true }
restate-wal-protocol = { workspace = true }

anyhow = { workspace = true }
bytes = { workspace = true }
bytestring = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = ["derive", "env", "wrap_help", "color"] }
clap-verbosity-flag = { workspace = true }
clap-stdin = "0.5.1"
cling = { workspace = true }
crossterm = { version = "0.27.0" }
ctrlc = { version = "3.4" }
derive_more = { workspace = true }
futures-util = { workspace = true }
hyper-util = { workspace = true }
itertools = { workspace = true }
json-patch = "2.0.0"
prost-types = { workspace = true }
rand = { workspace = true }
rlimit = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true, features = ["transport", "prost"] }
tonic-health = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }
tracing-log = { version = "0.2" }
tracing-subscriber = { workspace = true }
url = { workspace = true }

[build-dependencies]
vergen = { version = "8", default-features = false, features = [
    "build",
    "git",
    "gitcl",
    "cargo",
] }
