[package]
name = "restate-partition-store"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
test-util = ["restate-object-store-util/test-util", "restate-types/test-util"]

[dependencies]
restate-workspace-hack = { workspace = true }

restate-clock = { workspace = true }
restate-core = { workspace = true }
restate-errors = { workspace = true }
restate-object-store-util = { workspace = true }
restate-rocksdb = { workspace = true }
restate-serde-util = { workspace = true }
restate-storage-api = { workspace = true }
restate-types = { workspace = true }

ahash = { workspace = true }
anyhow = { workspace = true }
bilrost = { workspace = true }
bytes = { workspace = true }
bytestring = { workspace = true }
codederror = { workspace = true }
derive_more = { workspace = true }
enum-map = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
itertools = { workspace = true }
jiff = { workspace = true }
object_store = { workspace = true }
parking_lot = { workspace = true }
paste = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
rocksdb = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true, features = ["hex"] }
smartstring = { workspace = true }
static_assertions = { workspace = true }
strum = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
tokio-stream = { workspace = true }
tokio-util = { workspace = true, features = ["io-util"] }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
restate-core = { workspace = true, features = ["test-util"] }
restate-object-store-util = { workspace = true, features = ["test-util"] }
restate-rocksdb = { workspace = true, features = ["test-util"] }
restate-test-util = { workspace = true }
restate-types = { workspace = true, features = ["test-util"] }
restate-service-protocol-v4 = { workspace = true, features = ["entry-codec"] }
restate-storage-api = { workspace = true, features = ["test-util"] }

criterion = { workspace = true, features = ["async_tokio"] }
googletest = { workspace = true }
num-bigint = "0.4"
rand = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
test-log = { workspace = true }
tracing-subscriber = { workspace = true }

[[bench]]
name = "basic_benchmark"
harness = false
