[package]
name = "restate-serde-util"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
schema = ["dep:schemars", "dep:serde_json"]
proto = ["dep:prost", "dep:bytes"]

[dependencies]
restate-workspace-hack = { workspace = true }

bytes = { workspace = true, optional = true }
bytesize = { workspace = true }
http = { workspace = true }
http-serde = { workspace = true }
prost = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
serde_with = { workspace = true }
jiff = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }