[package]
name = "restate_tracing_instrumentation"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
options_schema = ["dep:schemars"]

[dependencies]
derive_builder = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
console-subscriber = { version = "0.1.10", optional = true }
opentelemetry = { workspace = true, features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.18", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.12" }
opentelemetry-semantic-conventions = "0.11"
opentelemetry-contrib = { version = "0.11", features = ["jaeger_json_exporter", "rt-tokio"] }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
tracing-opentelemetry = { workspace = true }
nu-ansi-term = "0.46.0"

[dev-dependencies]
tokio = { workspace = true }
