[package]
name = "restate_service_key_extractor"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
serde = ["dep:serde"]
expand = ["prost-reflect"]
json = ["expand", "prost-reflect/serde", "dep:serde_json", "dep:restate_serde_util"]

[dependencies]
arc-swap = { workspace = true }
bytes = { workspace = true }
prost = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }

serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

prost-reflect = { workspace = true, optional = true }

restate_serde_util = { workspace = true, optional = true }

[dev-dependencies]
prost-reflect = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }