[package]
name = "logserver-bench"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []

[dependencies]
restate-workspace-hack = { workspace = true }

restate-cli-util = { workspace = true }
restate-core = { workspace = true, features = ["message-util"] }
restate-errors = { workspace = true }
restate-log-server = { workspace = true, features = ["expose-internals"] }
restate-memory = { workspace = true }
restate-rocksdb = { workspace = true }
restate-serde-util = { workspace = true }
restate-time-util = { workspace = true }
restate-tracing-instrumentation = { workspace = true, features = ["rt-tokio"] }
restate-types = { workspace = true, features = ["clap"] }

anyhow = { workspace = true }
axum = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true, features = ["derive", "env", "color", "help", "wrap_help", "usage", "suggestions", "error-context", "std"] }
codederror = { workspace = true }
comfy-table = { workspace = true }
hdrhistogram = { version = "7.5.4" }
indexmap = { workspace = true }
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
rand = { workspace = true }
rlimit = { workspace = true }
rocksdb = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { workspace = true, features = ["unprefixed_malloc_on_supported_platforms"] }
tikv-jemalloc-ctl = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
