[package]
name = "restate_cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "restate-cli"
path = "src/main.rs"

[dependencies]
arrow-array = { version = "36.0.0" }
async-trait = { version = "0.1.68" }
bytes = { workspace = true }
bytestring = { workspace = true }
clap = { version = "4.1", features = ["derive"] }
datafusion = { version = "22.0.0" }
datafusion-cli = { version = "22.0.0" }
futures = { workspace = true }
hex = "0.4.3"
prost = { workspace = true }
prost-types = { workspace = true }
prost-reflect = { workspace = true, features = ["derive", "serde", "text-format"] }
restate_tracing_instrumentation = { workspace = true }
rustyline = "10.0"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
tonic = { workspace = true, features = ["default"] }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
prost-build = { workspace = true }
