[package]
name = "restate-queue"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
restate-fs-util = { workspace = true }

bincode = { version = "2.0.0-rc", default-features = false, features = ["std", "serde"] }
serde = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-util"] }

[dev-dependencies]
restate-types = { workspace = true, features = ["test-util"] }

criterion = { workspace = true, features = ["async_tokio"] }
tempfile = { workspace = true }

[[bench]]
name = "queue_benchmark"
harness = false
