[package]
name = "worker"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
assert2 = { workspace = true }
bytes = { workspace = true }
bytestring = { workspace = true }
common = { workspace = true }
consensus = { workspace = true }
drain = { workspace = true }
futures = { workspace = true }
ingress_grpc = { workspace = true }
invoker = { workspace = true }
journal = { workspace = true }
network = { workspace = true }
pin-project = { workspace = true }
thiserror = { workspace = true }
timer = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
opentelemetry_api = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
service_key_extractor = { workspace = true }
service_metadata = { workspace = true }
service_protocol = { workspace = true, features = ["codec"] }
storage_api = { workspace = true}
storage_rocksdb = { workspace = true}

[dev-dependencies]
test_utils = { workspace = true }
tracing-subscriber = { workspace = true }