[package]
name = "restate_worker"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
options_schema = ["dep:schemars", "restate_timer/options_schema", "restate_storage_rocksdb/options_schema", "restate_storage_grpc/options_schema", "restate_ingress_grpc/options_schema", "restate_invoker/options_schema"]

[dependencies]
anyhow = { workspace = true }
assert2 = { workspace = true }
bytes = { workspace = true }
bytestring = { workspace = true }
codederror = { workspace = true }
restate_types = { workspace = true }
derive_builder = { workspace = true }
restate_consensus = { workspace = true }
drain = { workspace = true }
futures = { workspace = true }
restate_ingress_grpc = { workspace = true }
restate_invoker = { workspace = true }
restate_network = { workspace = true }
pin-project = { workspace = true }
thiserror = { workspace = true }
restate_timer = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
opentelemetry_api = { workspace = true }
tracing = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
restate_service_key_extractor = { workspace = true }
restate_service_metadata = { workspace = true }
restate_service_protocol = { workspace = true, features = ["codec"] }
restate_storage_api = { workspace = true}
restate_storage_grpc = { workspace = true}
restate_storage_rocksdb = { workspace = true}
restate_worker_api = { workspace = true }

[dev-dependencies]
restate_test_util = { workspace = true }
tracing-subscriber = { workspace = true }
