[package]
name = "restate-cli"
version = "0.0.1-dev"
authors = { workspace = true }
description = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
publish = false
default-run = "restate"
build = "build.rs"

[features]
default = []

[dependencies]
restate-meta-rest-model = { workspace = true }
restate-serde-util = { workspace = true }

anyhow = { workspace = true }
arrow = { version = "49.0.0", default-features = false, features = ["ipc", "prettyprint"] }
async-trait = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
chrono-humanize = { version = "0.2.3" }
clap = { version = "4.1", features = ["derive", "env", "wrap_help", "color"] }
clap-verbosity-flag = { version = "2.0.1" }
cling = { version = "0.1.0", default-features = false, features = ["derive"] }
comfy-table = "7.1"
convert_case = "0.6"
ctrlc = { version = "3.4.1" }
dialoguer = { version = "0.11.0" }
dirs = { version = "5.0" }
dotenvy = "0.15"
futures = { workspace = true }
http = { workspace = true }
indicatif = "0.17.7"
indoc = { version = "2.0.4" }
is-terminal = { version = "0.4.9" }
itertools = { workspace = true }
octocrab = { version = "0.32.0", features = ["stream"] }
once_cell = { workspace = true }
reqwest = { version = "0.11.22", default-features = false, features = ["json", "rustls-tls"] }
serde = { workspace = true }
serde_json = { workspace = true }
termcolor = { version = "1.4.0" }
thiserror = { workspace = true }
tiny-gradient = { version = "0.1.0" }
tokio = { workspace = true, features = ["fs"] }
tracing = { workspace = true }
tracing-log = { version = "0.2.0" }
tracing-subscriber = { workspace = true }
unicode-width = { version = "0.1.11" }
url = { version = "2.4.1" }
zip = "0.6"
zip-extensions = "0.6"

[build-dependencies]
vergen = { version = "8.0.0", default-features = false, features = [
    "build",
    "git",
    "gitcl",
    "cargo",
] }

[lib]
bench = false

[[bin]]
name = "restate"
path = "src/main.rs"
