[package]
name = "restate-cli"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
publish = false
default-run = "restate"
build = "build.rs"

[features]
default = ["cloud"]
cloud = []

[dependencies]
restate-meta-rest-model = { workspace = true }
restate-serde-util = { workspace = true }
restate-service-protocol = { workspace = true, features = ["awakeable-id"] }
restate-types = { workspace = true }

anyhow = { workspace = true }
arrow = { version = "51.0.0", features = ["ipc", "prettyprint"] }
arrow_convert = { version = "0.6.6" }
axum = { workspace = true, default-features = false, features = ["http1", "query", "tokio"] }
bytes = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
chrono-humanize = { version = "0.2.3" }
clap = { version = "4.1", features = ["derive", "env", "wrap_help", "color"] }
clap-verbosity-flag = { version = "2.0.1" }
cling = { version = "0.1.0", default-features = false, features = ["derive"] }
comfy-table = "7.1"
convert_case = "0.6"
crossterm = { version = "0.27.0" }
ctrlc = { version = "3.4.1" }
dialoguer = { version = "0.11.0" }
dirs = { version = "5.0" }
dotenvy = "0.15"
figment = { version = "0.10.8", features = ["env", "toml"] }
futures = { workspace = true }
http = { workspace = true }
indicatif = "0.17.7"
indoc = { version = "2.0.4" }
itertools = { workspace = true }
octocrab = { version = "0.32.0", features = ["stream"] }
once_cell = { workspace = true }
open = "5.1.2"
reqwest = { version = "0.11.22", default-features = false, features = ["json","rustls-tls"] }
serde = { workspace = true }
serde_json = { workspace = true }
termcolor = { version = "1.4.0" }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
toml_edit = "0.22.12"
tracing = { workspace = true }
tracing-log = { version = "0.2.0" }
tracing-subscriber = { workspace = true }
typify = "0.1.0"
unicode-width = { version = "0.1.11" }
url = { version = "2.4.1" }
uuid = { workspace = true }
zip = "0.6"

[build-dependencies]
vergen = { version = "8.0.0", default-features = false, features = [
    "build",
    "git",
    "gitcl",
    "cargo",
] }

[lib]
bench = false

[[bin]]
name = "restate"
path = "src/main.rs"
