[package]
name = "restate-cli"
version = "0.0.1-dev"
authors = { workspace = true }
description = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
publish = false
default-run = "restate"
build = "build.rs"

[features]
default = []

[dependencies]
anyhow = { workspace = true }
clap = { version = "4.1", features = ["derive", "env", "wrap_help", "color"] }
clap-verbosity-flag = { version = "2.0.1" }
cling = { version = "0.1.0", default-features = false, features = ["derive"] }
comfy-table = "7.1"
dirs = { version = "5.0" }
dotenvy = "0.15"
indicatif = "0.17.7"
once_cell = { version = "1.18.0" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-log = { version = "0.2.0" }
is-terminal = { version = "0.4.9" }
http = { version = "1.0.0" }
tiny-gradient = { version = "0.1.0" }


[build-dependencies]
vergen = { version = "8.0.0", default-features = false, features = [
    "build",
    "git",
    "gitcl",
    "cargo",
] }

[lib]
bench = false

[[bin]]
name = "restate"
path = "src/main.rs"
