[package]
name = "restate-cli"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
publish = false
default-run = "restate"
build = "build.rs"

[features]
default = ["cloud"]
cloud = []

[dependencies]
restate-admin-rest-model = { workspace = true }
restate-cli-util = { workspace = true }
restate-serde-util = { workspace = true }
restate-service-protocol = { workspace = true, features = ["awakeable-id"] }
restate-types = { workspace = true }

anyhow = { workspace = true }
arc-swap = { workspace = true }
arrow = { version = "51.0.0", features = ["ipc", "prettyprint", "json"] }
arrow_convert = { version = "0.6.6" }
axum-0-6 = { package = "axum", version = "0.6.20", default-features = false, features = ["http1", "http2", "query", "tokio"] }
bytes = { workspace = true }
base62 = { version = "2.0.2" }
base64 = { workspace = true }
bs58 = { version = "0.5.0" }
chrono = { workspace = true }
chrono-humanize = { workspace = true }
clap = { workspace = true, features = ["derive", "env", "wrap_help", "color"] }
clap-verbosity-flag = { workspace = true }
cling = { workspace = true }
comfy-table = { workspace = true }
convert_case = "0.6"
crossterm = { workspace = true }
ctrlc = { version = "3.4.1" }
dialoguer = { workspace = true }
dirs = { version = "5.0" }
figment = { version = "0.10.8", features = ["env", "toml"] }
futures = { workspace = true }
http = { version = "1.1.0" }
http-0-2 = { package = "http", version = "0.2" }
hyper-0-14 = { package = "hyper", version = "0.14", features = ["server", "http2"] }
hyper-rustls-0-24 = { package = "hyper-rustls", version = "0.24.1", features = ["http2"] }
hyper-util = { version = "0.1", features = ["client-legacy", "http2", "server", "client", "tokio"] }
indicatif = "0.17.7"
indoc = { version = "2.0.4" }
itertools = { workspace = true }
jsonwebtoken = { version = "9.1.0" }
octocrab = { version = "0.32.0", features = ["stream"] }
open = "5.1.2"
reqwest = { version = "0.12.5", default-features = false, features = ["json", "rustls-tls", "stream"] }
reqwest-0-11 = { package = "reqwest", version = "0.11.22", default-features = false, features = ["json", "rustls-tls", "stream"] }
ring = { version = "0.17.8" }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
termcolor = { version = "1.4.0" }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
tokio-util = { workspace = true }
toml_edit = "0.22.12"
tower = { workspace = true }
tracing = { workspace = true }
typify = "0.1.0"
url = { workspace = true }
uuid = { workspace = true }
zip = "0.6"

[dev-dependencies]
restate-cli-util = { workspace = true, features = ["test-util"] }

[build-dependencies]
vergen = { version = "8.0.0", default-features = false, features = [
    "build",
    "git",
    "gitcl",
    "cargo",
] }

[lib]
bench = false

[[bin]]
name = "restate"
path = "src/main.rs"
