[package]
name = "restate_queue"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {workspace = true, features = ["fs", "io-util"]}
serde = {workspace = true}
restate_fs_util = {workspace = true}
bincode = "1.3"

[dev-dependencies]
tempfile = { workspace = true }
criterion = { version = "0.4.0", features = ["async_tokio"] }

[[bench]]
name = "queue_benchmark"
harness = false