[package]
name = "timer"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.3"
clap = { workspace = true }
common = { workspace = true }
drain = { workspace = true }
pin-project = { workspace = true }
priority-queue = "1.3.1"
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
futures-util = { workspace = true }
test_utils = { workspace = true }
tracing-subscriber = {workspace = true }