[package]
name = "restate_storage_rocksdb"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
options_schema = ["dep:schemars"]

[dependencies]
restate_common = {workspace = true}
bytes = {workspace = true}
bytestring = { workspace = true }
codederror = { workspace = true }
uuid = { workspace = true }
futures = {workspace = true}
futures-util = {workspace = true}
prost = {workspace = true}
schemars = { workspace = true, optional = true }
restate_errors = { workspace = true }
restate_storage_proto = { workspace = true, features = ["conversion"] }
restate_storage_api = { workspace = true }
serde = {workspace = true}
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
rocksdb = { workspace = true }
paste = { workspace = true}

[dev-dependencies]
tempfile = "3.4.0"
criterion = { version = "0.4.0", features = ["async_tokio"] }
num-bigint = "0.4"

[[bench]]
name = "basic_benchmark"
harness = false
