[package]
name = "storage_rocksdb"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {workspace = true}
bytes = {workspace = true}
bytestring = { workspace = true }
uuid = { workspace = true }
futures = {workspace = true}
futures-util = {workspace = true}
prost = {workspace = true}
storage_proto = {workspace = true}
storage_api = { workspace = true }
serde = {workspace = true}
tokio = { workspace = true }
tokio-stream = { workspace = true }
rocksdb = "0.20.1"

[dev-dependencies]
tempfile = "3.4.0"
criterion = { version = "0.4.0", features = ["async_tokio"] }

[[bench]]
name = "basic_benchmark"
harness = false
