[env]
RUST_TEST_THREADS = "1"

[alias]
xtask = "run --package xtask --"

[build]
# when changing these please also change .github/workflows/steps/release-build-setup.yml
rustflags = [
    "-C", "force-unwind-tables", # Include full unwind tables when aborting on panic
    "--cfg", "uuid_unstable", # Enable unstable Uuid
    "--cfg", "tokio_unstable", # Enable unstable tokio
]

[target.x86_64-unknown-linux-gnu]
# when changing these please also change .github/workflows/steps/release-build-setup.yml
rustflags = [
    "-C", "force-unwind-tables", # Include full unwind tables when aborting on panic
    "--cfg", "uuid_unstable", # Enable unstable Uuid
    "--cfg", "tokio_unstable", # Enable unstable tokio
]

[target.aarch64-unknown-linux-gnu]
rustflags = [
    "-C", "force-unwind-tables", # Include full unwind tables when aborting on panic
    "--cfg", "uuid_unstable", # Enable unstable Uuid
    "--cfg", "tokio_unstable", # Enable unstable tokio
    "-C" , "force-frame-pointers=yes", # Enable frame pointers to support Parca (https://github.com/parca-dev/parca-agent/pull/1805)
]

[target.x86_64-unknown-linux-musl]
rustflags = [
    "-C", "force-unwind-tables", # Include full unwind tables when aborting on panic
    "--cfg", "uuid_unstable", # Enable unstable Uuid
    "--cfg", "tokio_unstable", # Enable unstable tokio
    "-C", "link-self-contained=yes", # Link statically
]

[target.aarch64-unknown-linux-musl]
rustflags = [
    "-C", "force-unwind-tables", # Include full unwind tables when aborting on panic
    "--cfg", "uuid_unstable", # Enable unstable Uuid
    "--cfg", "tokio_unstable", # Enable unstable tokio
    "-C", "force-frame-pointers=yes", # Enable frame pointers to support Parca (https://github.com/parca-dev/parca-agent/pull/1805)
    "-C", "link-self-contained=yes", # Link statically
]
