[package]
name = "restate-node-protocol"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []

[dependencies]
restate-types = { workspace = true }
# merge schema creates with restate-types?
restate-schema = { workspace = true }

bytes = { workspace = true }
bytestring = { workspace = true }
derive_more = { workspace = true }
enum-map = { workspace = true }
flexbuffers = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true}
serde_with = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }

