[package]
name = "restate-node-protocol"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []

[dependencies]
restate-types = { workspace = true, features = ["serde"] }

anyhow = { workspace = true, optional = true }
bytes = { workspace = true, optional = true }
enum-map = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true}
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true, optional = true }

[build-dependencies]
prost-build = { workspace = true }

