[package]
name = "bifrost-benchpress"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
console = [
    "tokio/full",
    "tokio/tracing",
    "restate-tracing-instrumentation/console-subscriber",
]

[dependencies]
restate-workspace-hack = { workspace = true }

restate-bifrost = { workspace = true, features = ["memory-loglet", "local-loglet"] }
restate-core = { workspace = true, features = ["test-util"] }
restate-errors = { workspace = true }
restate-metadata-server = { workspace = true }
restate-rocksdb = { workspace = true }
restate-test-util = { workspace = true }
restate-tracing-instrumentation = { workspace = true, features = ["rt-tokio"] }
restate-ty = { workspace = true, features = ["test-util"] }
restate-types = { workspace = true, features = ["test-util", "clap"] }

anyhow = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true, features = ["derive", "env", "color", "help", "wrap_help", "usage", "suggestions", "error-context", "std"] }
codederror = { workspace = true }
figment = { version = "0.10.8", features = ["env", "toml"] }
futures = { workspace = true }
hdrhistogram = { version = "7.5.4" }
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
quanta = { version = "0.12.3" }
rlimit = { workspace = true }
rocksdb = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
static_assertions = { workspace = true }
strum = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
toml = { version = "0.8" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { workspace = true, features = ["unprefixed_malloc_on_supported_platforms"] }
