[package]
name = "ingress_common"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { workspace = true }

bytes = { workspace = true }
drain = { workspace = true }
futures = { workspace = true }
pin-project = { workspace = true }
opentelemetry_api = { workspace = true }
tower = { version = "0.4", features = ["util"] }
tonic = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }

[dev-dependencies]
mockall = "0.11"
test_utils = { workspace = true }
tokio-util = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }