[package]
name = "restate-metadata-server"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
test-util = []

[dependencies]
restate-workspace-hack = { workspace = true }

restate-core = { workspace = true }
restate-metadata-providers = { workspace = true, features = ["replicated"] }
restate-metadata-server-grpc = { workspace = true, features = ["grpc-client", "grpc-server"] }
restate-metadata-store = { workspace = true }
restate-rocksdb = { workspace = true }
restate-types = { workspace = true }

anyhow = { workspace = true }
arc-swap = { workspace = true }
assert2 = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
bytestring = { workspace = true }
chrono = { workspace = true }
derive_more = { workspace = true }
flexbuffers = { workspace = true }
futures = { workspace = true }
humantime = { workspace = true }
itertools = { workspace = true }
metrics = { workspace = true }
prost = { workspace = true }
prost-dto = { workspace = true }
protobuf = "2.28.0"
# Tikv is using the same version of raft and raft-proto. The released 0.7.0 is 2 years old and master contains a few
# improvements.
raft = { git = "https://github.com/tikv/raft-rs", rev = "2fbeee5b89b22c392da39435b79be9896acedd1d" }
raft-proto = { git = "https://github.com/tikv/raft-rs", rev = "2fbeee5b89b22c392da39435b79be9896acedd1d" }
rand = { workspace = true }
rocksdb = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
slog = { version = "2.7.0" }
static_assertions = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true, features = ["transport", "codegen", "prost"] }
tracing = { workspace = true }
tracing-slog = { version = "0.3.0" }
ulid = { workspace = true, features = ["serde"] }

[dev-dependencies]
restate-core = { workspace = true, features = ["test-util"] }
restate-rocksdb = { workspace = true, features = ["test-util"] }

googletest = { workspace = true }
tempfile = { workspace = true }
test-log = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }