# This file contains settings for `cargo hakari`.
# See https://docs.rs/cargo-hakari/latest/cargo_hakari/config for a full list of options.

hakari-package = "restate-workspace-hack"
workspace-hack-line-style = "workspace-dotted"

# Format version for hakari's output. Version 4 requires cargo-hakari 0.9.22 or above.
dep-format-version = "4"
resolver = "2"

# Add triples corresponding to platforms commonly used by developers here.
# https://doc.rust-lang.org/rustc/platform-support.html
platforms = [
    "x86_64-unknown-linux-gnu",
    "aarch64-apple-darwin",
]

# Write out exact versions rather than a semver range. (Defaults to false.)
# exact-versions = true

[traversal-excludes]
workspace-members = ["service-protocol-wireshark-dissector"]
third-party = [
    # excluded to avoid pulling in feature="test-util" by default for non-test builds
    { name = "tokio" },
    # excluded for Windows compatibility - rdkafka requires OpenSSL which doesn't build easily on Windows
    { name = "rdkafka" },
    { name = "rdkafka-sys" },
]
