[package]
name = "restate-metadata-server-grpc"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
test-util = []
grpc-client = ["tonic/transport", "tonic/gzip", "tonic/zstd"]
grpc-server = ["tonic/server"]

[dependencies]
restate-workspace-hack = { workspace = true }

restate-types = { workspace = true }
restate-ty = { workspace = true }

bytes = { workspace = true }
bytestring = { workspace = true }
derive_more = { workspace = true }
itertools = { workspace = true }
prost = { workspace = true }
prost-dto = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true, features = ["codegen"] }
tonic-prost = { workspace = true }
tracing = { workspace = true }
ulid = { workspace = true, features = ["serde"] }

[build-dependencies]
tonic-prost-build = { workspace = true }
