[package]
name = "restate-service-protocol-v4"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
entry-codec = ["dep:bytestring", "dep:assert2"]
message-codec = ["dep:bytes-utils", "dep:codederror", "dep:restate-errors", "dep:tracing", "dep:paste"]

[dependencies]
restate-workspace-hack = { workspace = true }

restate-errors = { workspace = true, optional = true }
restate-serde-util = { workspace = true }
restate-types = { workspace = true }

assert2 = { workspace = true, optional = true }
bytes = { workspace = true }
bytestring = { workspace = true, optional = true }
bytes-utils = { workspace = true, optional = true }
codederror = { workspace = true, optional = true }
paste = { workspace = true, optional = true }
prost = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true, optional = true }

[dev-dependencies]
restate-test-util = { workspace = true }
restate-types = { workspace = true, features = ["test-util"] }

[build-dependencies]
prost-build = { workspace = true }
prettyplease = "0.2"
serde_json = { workspace = true }
syn = { workspace = true }
typify = { workspace = true }
jsonptr = { workspace = true }
