[package]
name = "restate-storage-api"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
test-util = []

[dependencies]
restate-workspace-hack = { workspace = true }

restate-types = { workspace = true }

prost = { workspace = true }
prost-types = { workspace = true }
anyhow = { workspace = true }
bytes = { workspace = true }
bytestring = { workspace = true }
derive_more = { workspace = true }
futures = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
rangemap = { workspace = true }
opentelemetry = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }