[package]
name = "restate-storage-api"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
test-util = []

[dependencies]
restate-workspace-hack = { workspace = true }

restate-clock = { workspace = true }
restate-types = { workspace = true }

ahash = { workspace = true }
anyhow = { workspace = true }
bilrost = { workspace = true, features = ["smallvec"] }
bytes = { workspace = true }
bytestring = { workspace = true }
derive_more = { workspace = true, features = ["from", "into"] }
futures = { workspace = true }
opentelemetry = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
smallvec = { workspace = true }
static_assertions = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }
