[package]
name = "restate"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
description.workspace = true
default-run = "restate"

[features]
default = []
console = ["tokio/full", "tokio/tracing", "restate_tracing_instrumentation/console-subscriber"]
options_schema = ["dep:schemars", "restate_tracing_instrumentation/options_schema", "restate_meta/options_schema", "restate_worker/options_schema"]

[dependencies]
clap = { version = "4.1", features = ["derive", "env"] }
codederror = { workspace = true }
derive_builder = { workspace = true }
drain = { workspace = true }
figment = { version = "0.10.8", features = ["env", "yaml"] }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
serde_with = "2.2"
serde_yaml = "0.9"
futures-util = { workspace = true }
humantime = { workspace = true }
pin-project = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
restate_types = { workspace = true }
restate_errors = { workspace = true, features = ["include_doc"] }
restate_fs_util = { workspace = true }
restate_meta = { workspace = true }
restate_tracing_instrumentation = { workspace = true, features = ["rt-tokio"] }
restate_worker = { workspace = true }
