[package]
name = "restate-web-ui"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
workspace-hack = { version = "0.1", path = "../../workspace-hack" }

include_dir = "0.7.4"

[build-dependencies]
zip = "2.2.0"
