[package]
name = "restate_lambda_client"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
options_schema = ["dep:schemars", "restate_types/serde_schema"]

[dependencies]
restate_types = { workspace = true }
restate_schema_api = { workspace = true }
schemars = { workspace = true, optional = true }
derive_builder = { workspace = true }

base64 = { workspace = true }
futures = { workspace = true }
hyper = { workspace = true }
serde = { workspace = true }
http-serde = "1.1.2"
serde_json = { workspace = true }
serde_with = { workspace = true }
thiserror = { workspace = true }

aws-config = "0.56.1"
aws-sdk-lambda = "0.30.0"
lambda_http = "0.8.1"
